### ISSUE TITLE
Unrecognized environment variables in Windows

### ISSUE THREAD

**Issue by BryanMatheus** [carlosmaniero/jigjs#22]
I had a problem with environment variable in the project on Windows. The platform has a different interpretation of these variables. My recommendation: install [cross-env](https://www.npmjs.com/package/cross-env) on template. 💯

**Comment by carlosmaniero** [comment]
Cool!

I'll make the temporary fix that is about to just add the cross-env library. But jigjs could use command line --attributes instead of env var.

I don't have a Windows machine to test it. could you test If I release a new version with this fix?

Thanks :)

**Comment by carlosmaniero** [comment]
I released `jigjs@0.0.0-pre-alpha.31` with cross-env. I appreciate if you could test this latest version.

**Comment by bryan-matheus** [comment]
Cool! The bug was resolved!
